### ISSUE TITLE
Villager mob

### ISSUE THREAD

**Issue by IrineuMC** [wode490390/ClassicVillagePopulator#2]
The villager doesn't move, even with the mobplugin, I think he's bugged, would you fix it?

**Comment by AlecMcQuarrie** [comment]
I have the same problem. I don't know if it's linked correctly to mobplugin as other mobs from other things work

**Comment by wode490390** [comment]
Fixed in https://github.com/wode490390/ClassicVillagePopulator/commit/a33d0b1f3364f8fa570601c523164df284686c86.
